#pragma once

// Phase B foundation: the Workspace Tree model.
//
// Holds the flattened, expanded-only view of the music collections and keeps
// an independent keyboard cursor over it. Each node carries a STABLE id (the
// MPD playlist path where one exists) rather than being identified by its
// visible label, so Phase C can yank/paste by identity rather than by row.

#include <algorithm>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "app/state.hpp"

namespace termusic {

enum class TreeNodeType {
  Group,
  /// The two roots of the workspace tree. `vault` holds the media, `core`
  /// holds the configuration files: the tree IS the navigation, so neither
  /// root is a page tab.
  VaultRoot,
  CoreRoot,
  /// A settings entry under `core`. It behaves like a collection: selecting
  /// it loads its editor into the right pane.
  CoreSection,
  /// The whole real MPD media database. A read-only collection: it is never a
  /// saved playlist and never owns the files it lists.
  Database,
  /// The latest playback occurrences, newest first. Application-owned and
  /// read-only: it is generated by playback, never edited by hand.
  History,
  /// A REAL saved playlist read from MPD. Nothing else: the tree has no
  /// synthetic rows and no reserved names, so what is listed can be opened,
  /// played and (unless MPD refuses) edited.
  Playlist,
};

struct TreeNode {
  TreeNodeType type = TreeNodeType::Group;
  std::string id;     // stable identity; playlist path for saved playlists
  std::string label;  // display text only
  int depth = 0;
  bool expandable = false;
  bool expanded = true;
  /// Semantic kind, carried by the MODEL so the renderer never looks a section
  /// up by name: a `core` entry is either information or a settings module.
  /// Meaningless for every other node type.
  CoreSectionKind core_kind = CoreSectionKind::Settings;

  bool isCollection() const { return type != TreeNodeType::Group; }
};

class WorkspaceTree {
 public:
  WorkspaceTree() { rebuild(); }

  /// Replaces the saved-playlist children with real MPD playlist names/paths.
  void setPlaylists(std::vector<std::pair<std::string, std::string>> playlists) {
    playlists_ = std::move(playlists);
    rebuild();
  }

  /// Nodes that are currently visible (children of collapsed groups are not).
  const std::vector<TreeNode> &visible() const { return visible_; }

  int cursor() const { return cursor_; }
  const TreeNode *current() const {
    if (visible_.empty())
      return nullptr;
    return &visible_[static_cast<std::size_t>(cursor_)];
  }

  /// j / k. Clamped at both ends; never wraps.
  /// Index of the real media database node, or -1 when it is not shown.
  int databaseIndex() const {
    for (std::size_t index = 0; index < visible_.size(); ++index) {
      if (visible_[index].type == TreeNodeType::Database)
        return static_cast<int>(index);
    }
    return -1;
  }

  /// Index of the playback-history node, or -1 when it is not shown.
  int historyIndex() const {
    for (std::size_t index = 0; index < visible_.size(); ++index) {
      if (visible_[index].type == TreeNodeType::History)
        return static_cast<int>(index);
    }
    return -1;
  }

  /// Moves the cursor without clamping through unrelated rows.
  void setCursor(int index) {
    if (visible_.empty())
      return;
    cursor_ = std::clamp(index, 0, static_cast<int>(visible_.size()) - 1);
  }

  void moveCursor(int delta) {
    if (visible_.empty())
      return;
    cursor_ = std::clamp(cursor_ + delta, 0,
                         static_cast<int>(visible_.size()) - 1);
  }
  void toFirst() { cursor_ = 0; }
  void toLast() {
    cursor_ = std::max(0, static_cast<int>(visible_.size()) - 1);
  }
  /// Ctrl+d / Ctrl+u: move the cursor by roughly half a page. The viewport
  /// follows the cursor, so the cursor is never left off-screen.
  void halfPage(int direction, int page_rows) {
    moveCursor(direction * std::max(1, page_rows / 2));
  }

  /// l: expand a collapsed group. Returns true when it changed something, so
  /// the caller knows the key was consumed by folding rather than "open".
  bool expand() {
    if (visible_.empty())
      return false;
    TreeNode &node = editable_current();
    if (!node.expandable || node.expanded)
      return false;
    if (node.id == "group:playlists")
      playlists_expanded_ = true;
    else if (node.id == "vault")
      vault_expanded_ = true;
    else if (node.id == "core")
      core_expanded_ = true;
    // Expansion is a VISIBILITY change: focus stays on the folder, so `Enter`
    // twice is a deterministic collapse/expand pair and the row the user is
    // looking at never moves under them. `rebuild()` restores the cursor by
    // node id, which is what keeps that true across the new rows.
    rebuild();
    return true;
  }

  /// `h` on a FOLDER: collapse it when it is expanded. A leaf, or a folder that
  /// is already collapsed, is left alone so the caller keeps its own meaning for
  /// the key. Returns true when the tree consumed the gesture.
  bool collapseFocusedFolder() {
    const TreeNode *node = current();
    if (node == nullptr || !node->expandable || !node->expanded)
      return false;
    return collapse();
  }

  /// h: collapse an expanded group, otherwise move to the parent group.
  bool collapse() {
    if (visible_.empty())
      return false;
    const TreeNode node = *current();
    if (node.expandable && node.expanded) {
      if (node.id == "group:playlists")
        playlists_expanded_ = false;
      else if (node.id == "vault")
        vault_expanded_ = false;
      else if (node.id == "core")
        core_expanded_ = false;
      rebuild();
      return true;
    }
    // Move to the owning directory: the nearest expandable ancestor.
    for (int index = cursor_ - 1; index >= 0; --index) {
      const TreeNode &candidate = visible_[static_cast<std::size_t>(index)];
      if (candidate.expandable) {
        cursor_ = index;
        return true;
      }
    }
    return false;
  }

  /// Expands the directory the cursor is on, if it is collapsed. Used by the
  /// page shortcuts, which must reveal the root they jump to.
  void expandCurrentRoot() {
    if (visible_.empty())
      return;
    TreeNode &node = editable_current();
    if (!node.expandable || node.expanded)
      return;
    if (node.id == "vault")
      vault_expanded_ = true;
    else if (node.id == "core")
      core_expanded_ = true;
    else if (node.id == "group:playlists")
      playlists_expanded_ = true;
    rebuild();
  }

  /// Enter on a directory toggles it; Enter on a collection is the caller's
  /// job. Every expandable node is a directory -- the two roots included.
  bool toggleCurrentGroup() {
    if (const TreeNode *node = current();
        node != nullptr && node->expandable) {
      if (node->expanded)
        return collapse();
      return expand();
    }
    return false;
  }

 private:
  TreeNode &editable_current() {
    return visible_[static_cast<std::size_t>(cursor_)];
  }

  void rebuild() {
    const std::string previous_id =
        current() != nullptr ? current()->id : std::string{};
    visible_.clear();

    // Two roots only, like a filesystem: `vault` is the media, `core` is the
    // configuration. Everything else hangs below them, and MPD's own queue is
    // deliberately absent -- it is an internal playback mechanism, not
    // something the user browses.
    visible_.push_back(TreeNode{TreeNodeType::VaultRoot, "vault", "Vault", 0,
                                true, vault_expanded_});
    if (vault_expanded_) {
      visible_.push_back(TreeNode{TreeNodeType::Database, "library", "Library",
                                  1, false, true});
      visible_.push_back(TreeNode{TreeNodeType::History, "history", "History",
                                  1, false, true});
      visible_.push_back(TreeNode{TreeNodeType::Group, "group:playlists",
                                  "PlayLists", 1, true, playlists_expanded_});
      if (playlists_expanded_) {
        // ONLY real saved playlists. MPD's runtime queue is the backend's own
        // mechanism for playing a snapshot; it is not a collection and gets no
        // row here. A saved playlist called "default" is user data and is
        // listed like any other -- there is no synthetic node to collide with.
        for (const auto &[id, label] : playlists_)
          visible_.push_back(
              TreeNode{TreeNodeType::Playlist, id, label, 2, false, true});
      }
    }

    visible_.push_back(TreeNode{TreeNodeType::CoreRoot, "core", "Core", 0,
                                true, core_expanded_});
    if (core_expanded_) {
      for (const ConfigFileEntry &entry : kCoreSections)
        visible_.push_back(TreeNode{TreeNodeType::CoreSection,
                                    std::string(entry.id),
                                    std::string(entry.label), 1, false, true,
                                    entry.kind});
    }

    // Restore the cursor by identity where possible, else clamp.
    cursor_ = 0;
    if (!previous_id.empty()) {
      for (std::size_t index = 0; index < visible_.size(); ++index) {
        if (visible_[index].id == previous_id) {
          cursor_ = static_cast<int>(index);
          break;
        }
      }
    }
    cursor_ = std::clamp(cursor_, 0,
                         std::max(0, static_cast<int>(visible_.size()) - 1));
  }

 private:
  std::vector<std::pair<std::string, std::string>> playlists_;
  std::vector<TreeNode> visible_;
  int cursor_ = 0;
  bool vault_expanded_ = true;
  /// `core` starts collapsed: the workspace opens on the media, and the
  /// configuration directory is one keystroke away, exactly like a file
  /// manager.
  bool core_expanded_ = false;
  bool playlists_expanded_ = true;
};

} // namespace termusic
